#!/usr/bin/env python3
"""Build docs/research/chat-commands.html — the searchable command reference.

Same data as the markdown tables in docs/research/chat-commands.md, rendered as
a filterable page. Run it from the repository root, with the rAthena tree
present (`make server-up` clones it):

    python3 tools/chatcmds/build_page.py

Inputs:
    tools/chatcmds/page.template.html   layout, styles and the filter UI
    tools/chatcmds/slash.json           the / commands, hand-maintained
    the rAthena tree                    the @ commands, via gen.py

The @ half is read straight from the server we build, so it cannot drift. The
/ half cannot be generated — no single file on either side holds it — so it is
maintained by hand in slash.json and each row carries its source.

The template is deliberately free of <!doctype>, <html>, <head> and <body>: it
doubles as the source for the published artifact, whose host supplies those.
This script adds them (plus charset and viewport) when writing the standalone
file, so the page in docs/ also opens correctly straight off disk.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen  # noqa: E402  (path set above)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = "docs/research/chat-commands.html"

# Wrapper for the standalone file. Without the charset the em dashes and
# ellipses in the help text mis-decode when the file is opened over file://.
HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Generated by tools/chatcmds/build_page.py — do not edit by hand.
     Content source: docs/research/chat-commands.md -->
"""
# The template runs <title>/<link>/<style> straight into the markup, so the
# head/body boundary goes after the stylesheet. Browsers would infer it, but an
# unclosed <head> with a closing </body> is not a document worth committing.
BOUNDARY = "</style>"
SPLIT = "</style>\n</head>\n<body>"
TAIL = "\n</body>\n</html>\n"


def at_commands():
    """The @ half, shaped for the page: name, aliases, syntax, effect, group."""
    cmds = gen.parse_atcommands(f"{gen.R}/conf/atcommands.yml")
    groups = gen.parse_groups(f"{gen.R}/conf/groups.yml")
    reg = gen.registered(f"{gen.R}/src/map/atcommand.cpp")

    names = set(c["name"] for c in cmds)
    if names ^ reg:
        print("WARNING: atcommands.yml and atcommand.cpp disagree — "
              f"yml-only={sorted(names - reg)} code-only={sorted(reg - names)}",
              file=sys.stderr)

    # Lowest group granting each command. One a group never lists is reachable
    # only through the `all_commands` permission, which is Admin.
    eff = {g: gen.resolve(groups, g, "commands") for g in groups}
    grant = {}
    for g in sorted(groups.values(), key=lambda x: (x["level"], x["id"])):
        for c in eff[g["name"]]:
            grant.setdefault(c, g)

    rows, seen = [], set()
    for c in cmds:
        if c["name"] in seen:  # atcommands.yml lists refineui twice
            continue
        seen.add(c["name"])
        params, desc = gen.split_help(c["help"])
        g = grant.get(c["name"])
        rows.append({
            "n": c["name"],
            "a": c["aliases"],
            "s": params,
            "d": " ".join(" ".join(desc).split()),
            "g": g["id"] if g else 99,
            "gn": g["name"] if g else "Admin",
        })
    rows.sort(key=lambda r: r["n"])

    meta = [{"id": g["id"], "name": g["name"], "level": g["level"],
             "inherit": g["inherit"], "own": len(g["commands"]),
             "eff": len(gen.resolve(groups, g["name"], "commands")),
             "all": "all_commands" in g["perms"]}
            for g in sorted(groups.values(), key=lambda x: (x["level"], x["id"]))]
    return {"at": rows, "groups": meta}


def main():
    if not os.path.isdir(gen.R):
        sys.exit(f"{gen.R} is missing — run `make server-up` first, and this "
                 "script from the repository root.")

    at = at_commands()
    slash = json.load(open(f"{HERE}/slash.json", encoding="utf-8"))
    page = open(f"{HERE}/page.template.html", encoding="utf-8").read()

    for token, value in (("/*__AT__*/null", at), ("/*__SLASH__*/null", slash)):
        if token not in page:
            sys.exit(f"template has lost its {token} placeholder")
        page = page.replace(token, json.dumps(value, separators=(",", ":")))

    # Keep the two counts the copy quotes in step with the data.
    total = len(at["at"]) + len(slash)
    page = page.replace("Search 386 commands", f"Search {total} commands")

    if page.count(BOUNDARY) != 1:
        sys.exit(f"expected exactly one {BOUNDARY} in the template")
    page = page.replace(BOUNDARY, SPLIT)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEAD + page + TAIL)

    print(f"{OUT}: {len(at['at'])} at-commands + {len(slash)} slash commands "
          f"= {total}, {(len(page) + len(HEAD) + len(TAIL)) // 1024}KB")


if __name__ == "__main__":
    main()
