// Package items maps item ids to the names the interface shows.
//
// The archive's own table is Korean and the inventory packet carries ids
// only, so the client has to hold the names. These are rAthena's English
// item names, generated by tools/itemnames/gen.py from the same server tree
// the client talks to, which keeps the ids and the names in step.
//
// They are embedded as a data file rather than written as Go source: there
// are close to thirty thousand of them, and a map literal that size is a
// megabyte of code nobody can read.
package items

import (
	_ "embed"
	"strconv"
	"strings"
	"sync"
)

//go:embed names.txt
var namesData string

// Category is which of the inventory's three tabs an item belongs on.
type Category string

// The three tabs, matching the strings the generator writes.
const (
	CategoryUsable Category = "item"
	CategoryEquip  Category = "equip"
	CategoryEtc    Category = "etc"
)

// Info is what the table knows about one item.
type Info struct {
	Name     string
	Category Category

	// Resource is the icon's file name in the archive, which is Korean for
	// everything old enough to have one. Empty when the archive's table has
	// no entry, which is most of what has been added since.
	Resource string
}

var (
	once  sync.Once
	table map[uint32]Info
)

// load parses the table on first use, so a client that never opens the
// inventory never pays for it.
func load() {
	table = make(map[uint32]Info, 30000)

	for line := range strings.Lines(namesData) {
		fields := strings.Split(strings.TrimSuffix(line, "\n"), "\t")
		if len(fields) < 4 {
			continue
		}

		id, err := strconv.ParseUint(fields[0], 10, 32)
		if err != nil {
			continue
		}

		table[uint32(id)] = Info{
			Name:     fields[1],
			Category: Category(fields[2]),
			Resource: fields[3],
		}
	}
}

// Lookup returns everything the table knows about an item, and whether it
// knows it at all.
func Lookup(id uint32) (Info, bool) {
	once.Do(load)

	info, ok := table[id]

	return info, ok
}

// Name returns an item's name, or an empty string for an id this table does
// not know — a newer item than the tree this was generated from. Callers show
// the id in that case rather than nothing at all.
func Name(id uint32) string {
	once.Do(load)

	return table[id].Name
}

// CategoryOf returns which tab an item belongs on. An item the table does not
// know goes to etc, which is where anything uncategorised belongs anyway.
func CategoryOf(id uint32) Category {
	once.Do(load)

	if info, ok := table[id]; ok && info.Category != "" {
		return info.Category
	}

	return CategoryEtc
}

// Count is how many items the table holds, for tests that check the generator
// produced something rather than an empty file.
func Count() int {
	once.Do(load)

	return len(table)
}
