// Package items maps item ids to the names the interface shows.
//
// The archive's own table is Korean and the inventory packet carries ids
// only, so the client has to hold the names. These are rAthena's English
// item names, generated by tools/itemnames/gen.py from the same server tree
// the client talks to, which keeps the ids and the names in step.
//
// They are embedded as a data file rather than written as Go source: there
// are close to thirty thousand of them, and a map literal that size is a
// megabyte of code nobody can read.
package items

import (
	_ "embed"
	"strconv"
	"strings"
	"sync"
)

//go:embed names.txt
var namesData string

var (
	once  sync.Once
	names map[uint32]string
)

// load parses the table on first use, so a client that never opens the
// inventory never pays for it.
func load() {
	names = make(map[uint32]string, 30000)

	for line := range strings.Lines(namesData) {
		id, name, ok := strings.Cut(strings.TrimSuffix(line, "\n"), "\t")
		if !ok {
			continue
		}

		parsed, err := strconv.ParseUint(id, 10, 32)
		if err != nil {
			continue
		}

		names[uint32(parsed)] = name
	}
}

// Name returns an item's name, or an empty string for an id this table does
// not know — a newer item than the tree this was generated from. Callers show
// the id in that case rather than nothing at all.
func Name(id uint32) string {
	once.Do(load)

	return names[id]
}

// Count is how many items the table holds, for tests that check the generator
// produced something rather than an empty file.
func Count() int {
	once.Do(load)

	return len(names)
}
