#!/usr/bin/env python3
"""Generate the skill tables the server does not send from the client's own.

What arrives from the server is what a character has: which skills, at what
level, with what range. What it never sends is what the interface needs to draw
them — where a skill sits in the skill window, what it must be learned after,
and what it looks like when it goes off. That lives in the client's own
compiled Lua, and this reads it.

    skillinfoz/skillid.lub                 name -> id
    skillinfoz/skillinfolist.lub           per skill, including _NeedSkillList
    skillinfoz/skilltreeview.lub           the window's grid, per job
    skilleffectinfo/skilleffectinfolist.lub  the effect a skill plays
    skilleffectinfo/effectid.lub           effect names
    skilleffectinfo/actorstate.lub         the motion the caster makes

Deliberately not generated: max level, SP cost and range. The server sends all
three, and the client's copies disagree with it — 41 skills on max level and 20
on SP, checked against this server's own skill_db. Baking them in would mean
offering a level the server refuses and printing a cost it does not charge.

A skill this server does not have is left out. The client's data is newer than
the server tree it is talking to — 131 skills here are in the archive and not
in rAthena — and a skill the server never lists can never appear in a window or
be spent a point on. They are dropped against names.go, which is generated from
the server, so the two stay in step by construction.

Usage:
    gen.py <lua dir> <jobidentity.lub> <names.go> > skilltables.go
"""

import os
import re
import sys

import lua

# The tree is keyed by a global this build of the client spells differently
# from the one the tree file expects.
JOB_TABLE_ALIAS = 'JOBID'

# The skill window's grid, which the slot numbers count across.
TREE_COLUMNS = 7


def read(lua_dir, jobidentity):
    """Every table, with the cross-file globals each one needs already set."""
    seed = {}
    for name in ('skillid', 'effectid', 'actorstate'):
        seed.update(lua.run(os.path.join(lua_dir, name + '.lub')))

    jobs = lua.run(jobidentity)
    seed[JOB_TABLE_ALIAS] = jobs.get('JTtbl') or jobs.get(JOB_TABLE_ALIAS) or {}

    info = lua.run(os.path.join(lua_dir, 'skillinfolist.lub'), seed)
    tree = lua.run(os.path.join(lua_dir, 'skilltreeview.lub'), seed)
    effect = lua.run(os.path.join(lua_dir, 'skilleffectinfolist.lub'), seed)

    return seed, info['SKILL_INFO_LIST'], tree['SKILL_TREEVIEW_FOR_JOB'], \
        effect['SKILL_EFFECT_INFO_LIST']


def ints(pairs):
    """A Lua array of {skill, level} pairs as a list of (skill, level)."""
    out = []
    for entry in pairs.values():
        if not isinstance(entry, dict):
            continue
        skill = entry.get(1)
        level = entry.get(2)
        if skill is None:
            continue
        out.append((int(skill), int(level or 0)))

    return out


def known_skills(names_go):
    """Every skill id the server-generated name table holds."""
    source = open(names_go, encoding='utf-8').read()

    return {int(m.group(1)) for m in re.finditer(r'^\t(\d+):\s+"', source, re.M)}


def main():
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2

    seed, info, tree, effect = read(sys.argv[1], sys.argv[2])
    known = known_skills(sys.argv[3])
    dropped = 0
    names = {int(v): k for k, v in seed['SKID'].items()}
    effect_names = {int(v): k for k, v in seed['EFID'].items()}

    out = [
        "// Code generated by tools/skilltables/gen.py. DO NOT EDIT.",
        "//",
        "// Source: the client's own skillinfolist.lub, skilltreeview.lub and",
        "// skilleffectinfolist.lub, extracted from the GRF. Regenerate after a",
        "// client data update.",
        "",
        "package skills",
        "",
    ]

    # Prerequisites.
    needs = {int(sid): ints(entry['_NeedSkillList'])
             for sid, entry in info.items()
             if isinstance(entry.get('_NeedSkillList'), dict)}
    needs = {k: [n for n in v if n[0] in known]
             for k, v in needs.items() if v and k in known}
    dropped += sum(1 for v in needs.values() if not v)
    needs = {k: v for k, v in needs.items() if v}

    out += [
        "// Need is a skill that has to be learned first, and to what level.",
        "type Need struct {",
        "\tSkill uint16",
        "\tLevel uint8",
        "}",
        "",
        "// needs is what each skill has to be learned after.",
        "//",
        "// The server refuses a skill point spent on something not yet reachable,",
        "// and says nothing about why; this is what lets the button be greyed out",
        "// instead of the request being sent and silently dropped.",
        "var needs = map[uint16][]Need{",
    ]
    for sid in sorted(needs):
        pairs = ", ".join(f"{{{s}, {l}}}" for s, l in needs[sid])
        out.append(f"\t{sid}: {{{pairs}}}, // {names.get(sid, '?')}")
    out += ["}", ""]

    # The window's grid.
    out += [
        "// TreeSlot is where a skill sits in the skill window: the slot counts",
        "// across the grid, seven to a row.",
        "type TreeSlot struct {",
        "\tSlot  int",
        "\tSkill uint16",
        "}",
        "",
        f"// TreeColumns is how wide the skill window's grid is.",
        f"const TreeColumns = {TREE_COLUMNS}",
        "",
        "// tree is the grid each job's skill window lays out.",
        "var tree = map[int][]TreeSlot{",
    ]
    total = 0
    for job in sorted(tree, key=lambda j: int(j)):
        slots = tree[job]
        if not slots:
            continue
        kept = [(int(slot), int(skill)) for slot, skill in slots.items()
                if int(skill) in known]
        dropped += len(slots) - len(kept)
        if not kept:
            continue

        rows = ", ".join(f"{{{slot}, {skill}}}" for slot, skill in sorted(kept))
        total += len(kept)
        out.append(f"\t{int(job)}: {{{rows}}},")
    out += ["}", ""]

    # What a skill looks like when it goes off.
    out += [
        "// Effect is what a skill plays when it is cast: the motion the caster",
        "// makes, the effect drawn on the caster and on the target, and the sounds",
        "// that go with them.",
        "//",
        "// Only the skills whose look is not the default carry one.",
        "type Effect struct {",
        "\tCastMotion   int",
        "\tOnCaster     []int",
        "\tOnTarget     []int",
        "\tCasterSound  string",
        "\tTargetSound  string",
        "}",
        "",
        "var effects = map[uint16]Effect{",
    ]
    for sid in sorted(effect, key=lambda s: int(s)):
        e = effect[sid]
        caster = [int(v) for v in (e.get('effectID') or {}).values()]
        target = [int(v) for v in (e.get('targetEffectID') or {}).values()]
        motion = int(e.get('beginMotionType') or -1)
        cs = (e.get('waveFileName') or "").replace("\\", "\\\\")
        ts = (e.get('targetWaveFileName') or "").replace("\\", "\\\\")

        # An entry that says nothing is one the caller cannot tell from a
        # skill with no effect at all.
        if int(sid) not in known or (not caster and not target and not cs
                                     and not ts and motion < 0):
            dropped += 1
            continue

        out.append(
            f'\t{int(sid)}: {{CastMotion: {motion}, '
            f'OnCaster: []int{{{", ".join(map(str, caster))}}}, '
            f'OnTarget: []int{{{", ".join(map(str, target))}}}, '
            f'CasterSound: "{cs}", TargetSound: "{ts}"}}, // {names.get(int(sid), "?")}'
        )
    out += ["}", ""]

    print("\n".join(out))
    print(
        f"// {len(needs)} skills with prerequisites, {total} tree slots across "
        f"{len([j for j in tree if tree[j]])} jobs, {len(effect)} skills with an effect, "
        f"{len(effect_names)} effect names, {dropped} entries dropped as "
        f"unknown to this server or empty",
        file=sys.stderr,
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
