#!/usr/bin/env python3
"""Generate what a skill's tooltip says, from rAthena's skill database.

The skill list packet carries five things: the id, the level learned, the SP
it costs, its range and its targeting bits. That is what the window can show
without help, and it is not much — a player looking at Stone Curse learns
that it is active, costs SP and reaches two cells, and nothing about it being
Earth magic that needs a Red Gemstone and takes a second to cast.

The rest is in the server's own database. Not in the archive: both copies of
skilldescript.lub this client ships are Korean, so the prose the original
draws is no use under an English name, and there is no English set anywhere in
it. What rAthena has instead is every number, in English, for the same server
tree the client is talking to — which is where names.go already comes from, so
the two stay in step by construction.

Written as Go source rather than an embedded data file: this is a few hundred
kilobytes where the item table is tens of megabytes, and a table small enough
to read is worth being able to read.

    python3 tools/skillinfo/gen.py <rathena>/db/re/skill_db.yml \
        <rathena>/db/re/item_db_etc.yml [more item_db files...] \
        > internal/game/skills/info.go
"""

import re
import sys

HEADER = '''// Code generated by tools/skillinfo/gen.py. DO NOT EDIT.

package skills

// Info is what the server's database says about a skill beyond what it sends
// with a character's skill list.
//
// The packet carries the id, the level, the SP, the range and the targeting
// bits. Everything here is the rest of it: what a skill is, what it is made
// of, how long it takes and what it spends.
//
// The numbers that vary by level are held as one entry per level. Most do not
// vary, and those are held as a single entry rather than the same figure ten
// times over — At reads the last one for a level past the end, which is the
// same answer either way.
type Info struct {
	// Kind is Magic, Weapon or Misc, and Target what it may be aimed at.
	Kind   string
	Target string

	// Element is what it hits with. A few skills change element by level and
	// carry one entry each.
	Element []string

	// Hits is how many blows it lands, and the four times are in
	// milliseconds: the cast, the part of the cast nothing can shorten, the
	// wait before another skill, and the skill's own cooldown.
	Hits      []int
	CastMs    []int
	FixedMs   []int
	DelayMs   []int
	CooldownMs []int

	// Catalyst is what it consumes to go off, which the server refuses the
	// cast without and does not say in advance.
	Catalyst []Cost
}

// Cost is one thing a skill spends.
type Cost struct {
	Item   string
	Amount int
}

// At reads a per-level figure, in the levels a player counts from — one for
// the first.
//
// A level past the end reads the last entry rather than nothing: a table with
// one entry is a figure that does not vary, and that is how most of them are
// held.
func At(levels []int, level int) (int, bool) {
	if len(levels) == 0 {
		return 0, false
	}

	if level < 1 {
		level = 1
	}
	if level > len(levels) {
		level = len(levels)
	}

	return levels[level-1], true
}

// ElementAt is the same for the element.
func ElementAt(elements []string, level int) string {
	if len(elements) == 0 {
		return ""
	}

	if level < 1 {
		level = 1
	}
	if level > len(elements) {
		level = len(elements)
	}

	return elements[level-1]
}

// InfoOf is what the database says about a skill, and whether it says
// anything: a skill newer than the tree this was generated from has no entry.
func InfoOf(id uint16) (Info, bool) {
	info, ok := info[id]

	return info, ok
}

// InfoCount is how many skills the table holds, for tests that check the
// generator produced something rather than an empty map.
func InfoCount() int {
	return len(info)
}

var info = map[uint16]Info{
'''

FOOTER = '''}
'''

# The fields that may be written either as one figure or as one per level, and
# the key each level entry carries its value under.
LEVELLED = {
    "Element": "Element",
    "HitCount": "Count",
    "CastTime": "Time",
    "FixedCastTime": "Time",
    "AfterCastActDelay": "Time",
    "Cooldown": "Time",
}

# What each becomes in the Go struct.
FIELDS = {
    "HitCount": "Hits",
    "CastTime": "CastMs",
    "FixedCastTime": "FixedMs",
    "AfterCastActDelay": "DelayMs",
    "Cooldown": "CooldownMs",
}


def indent_of(line):
    return len(line) - len(line.lstrip(" "))


def read_item_names(paths):
    """AegisName to display name, which is how skill_db names a catalyst."""
    names = {}

    for path in paths:
        aegis = None

        with open(path, encoding="utf-8") as handle:
            for line in handle:
                if match := re.match(r"\s*-?\s*AegisName:\s*(\S+)\s*$", line):
                    aegis = match.group(1).strip("\"'")
                    continue

                if aegis and (match := re.match(r"\s*Name:\s*(.+?)\s*$", line)):
                    names[aegis] = match.group(1).strip("\"'")
                    aegis = None

    return names


def read_skills(path):
    """Every skill in the database, as {id: {field: value}}.

    A reader for the shape this file is in rather than for YAML: two-space
    indents, no anchors, no flow style, and every list an entry per line. What
    it has to tell apart is a field written as one figure from the same field
    written as one figure per level, which is the whole of the difficulty.
    """
    skills = {}

    current = None
    block = None      # the levelled field being collected
    levels = None     # its entries, by level
    catalyst = None   # the ItemCost list being collected
    in_requires = False

    def flush():
        if block is not None and levels:
            current[block] = [levels[level] for level in sorted(levels)]

    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if not line.strip() or line.lstrip().startswith("#"):
                continue

            indent = indent_of(line)
            text = line.strip()

            if match := re.match(r"-\s+Id:\s*(\d+)\s*$", text):
                flush()
                block, levels, catalyst, in_requires = None, None, None, False
                current = {}
                skills[int(match.group(1))] = current
                continue

            if current is None:
                continue

            # Out of whatever was being collected.
            if indent <= 4:
                flush()
                block, levels = None, None

                if indent == 4:
                    in_requires = False
                    catalyst = None

            if block is not None:
                key = LEVELLED[block]

                if match := re.match(r"-\s+Level:\s*(\d+)\s*$", text):
                    levels[int(match.group(1))] = None
                    continue

                if match := re.match(rf"{key}:\s*(\S+)\s*$", text):
                    if levels:
                        levels[max(levels)] = match.group(1).strip("\"'")
                    continue

                continue

            if catalyst is not None:
                if match := re.match(r"-\s+Item:\s*(\S+)\s*$", text):
                    catalyst.append([match.group(1).strip("\"'"), 1])
                    continue

                if match := re.match(r"Amount:\s*(\d+)\s*$", text):
                    if catalyst:
                        catalyst[-1][1] = int(match.group(1))
                    continue

                continue

            if indent == 4 and text == "Requires:":
                in_requires = True
                continue

            if in_requires and indent == 6 and text == "ItemCost:":
                catalyst = current.setdefault("ItemCost", [])
                continue

            if indent != 4:
                continue

            if match := re.match(r"(\w+):\s*(.*)$", text):
                field, value = match.group(1), match.group(2).strip()

                if field in LEVELLED:
                    if value:
                        current[field] = [value.strip("\"'")]
                    else:
                        block, levels = field, {}
                    continue

                if field in ("Type", "TargetType") and value:
                    current[field] = value.strip("\"'")

    flush()

    return skills


def go_ints(values):
    """A per-level list of numbers, or nothing when the field is absent."""
    numbers = []
    for value in values:
        try:
            numbers.append(int(value))
        except (TypeError, ValueError):
            return None

    # Held as one entry when it does not vary, which is most of them.
    if numbers and all(n == numbers[0] for n in numbers):
        numbers = numbers[:1]

    return numbers


def go_strings(values):
    words = [v for v in values if v]
    if words and all(w == words[0] for w in words):
        words = words[:1]

    return words


def quoted(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    skills = read_skills(sys.argv[1])
    items = read_item_names(sys.argv[2:])

    if not skills:
        print("no skills found — is that a skill_db.yml?", file=sys.stderr)
        return 1

    out = [HEADER]
    written = 0
    unknown_items = set()

    for skill_id in sorted(skills):
        entry = skills[skill_id]
        parts = []

        if kind := entry.get("Type"):
            parts.append("Kind: %s" % quoted(kind))
        if target := entry.get("TargetType"):
            parts.append("Target: %s" % quoted(target))

        if elements := go_strings(entry.get("Element", [])):
            parts.append("Element: []string{%s}" %
                         ", ".join(quoted(e) for e in elements))

        for field, name in FIELDS.items():
            numbers = go_ints(entry.get(field, []))
            if numbers:
                parts.append("%s: []int{%s}" %
                             (name, ", ".join(str(n) for n in numbers)))

        costs = []
        for aegis, amount in entry.get("ItemCost", []):
            name = items.get(aegis)
            if name is None:
                unknown_items.add(aegis)
                # The technical name reads better than nothing: a player can
                # see it is a gemstone even if it is spelt with an underscore.
                name = aegis.replace("_", " ")

            costs.append("{Item: %s, Amount: %d}" % (quoted(name), amount))

        if costs:
            parts.append("Catalyst: []Cost{%s}" % ", ".join(costs))

        if not parts:
            continue

        out.append("\t%d: {%s},\n" % (skill_id, ", ".join(parts)))
        written += 1

    out.append(FOOTER)
    sys.stdout.write("".join(out))

    print("generated %d skills of %d, %d item names" %
          (written, len(skills), len(items)), file=sys.stderr)
    if unknown_items:
        print("catalysts not in the item database: %s" %
              ", ".join(sorted(unknown_items)), file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
