#!/usr/bin/env python3
"""Generate the skill id to name table from rAthena's skill database.

The client would normally take these from the archive, but this archive's
names are Korean: skillnametable.txt maps a technical name like NV_BASIC to a
EUC-KR display name, and there is no English set in it. The packet does not
help either — from PACKETVER 20190807 the skill list dropped its name field,
so the client is expected to know them.

rAthena's skill_db.yml carries an English Description per id, which is where
these come from. Run this against the server tree the client is built to talk
to, so the ids and the names agree with what it will actually send.

    python3 tools/skillnames/gen.py <path-to-rathena>/db/re/skill_db.yml \
        > internal/game/skills/names.go
"""

import re
import sys

HEADER = '''// Code generated by tools/skillnames/gen.py. DO NOT EDIT.

// Package skills maps skill ids to the names the interface shows.
//
// The archive's own table is Korean and, from PACKETVER 20190807, the skill
// list packet no longer carries names at all — so the client has to hold
// them. These are rAthena's English descriptions, generated from the same
// server tree the client talks to, which keeps the ids and the names in step.
package skills

// names is every skill the server knows, by id.
var names = map[uint16]string{
'''

MIDDLE = '''}

// sprites is each skill's technical name in lower case, which is what its
// icon file is called: item/nv_basic.bmp.
var sprites = map[uint16]string{
'''

FOOTER = '''}

// Name returns a skill's name, or an empty string for an id the server knows
// and this table does not — a newer skill than the tree this was generated
// from. Callers show the id in that case rather than nothing at all.
func Name(id uint16) string {
	return names[id]
}

// Sprite returns the file name of a skill's icon, without extension, or an
// empty string for an id this table does not know.
func Sprite(id uint16) string {
	return sprites[id]
}

// Count is how many skills the table holds, for tests that check the
// generator produced something rather than an empty map.
func Count() int {
	return len(names)
}
'''


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    entries = {}
    sprites = {}
    skill_id = None
    technical = None

    with open(sys.argv[1], encoding="utf-8") as handle:
        for line in handle:
            if match := re.match(r"\s*-\s+Id:\s*(\d+)\s*$", line):
                skill_id = int(match.group(1))
                technical = None
                continue

            if skill_id is None:
                continue

            if match := re.match(r"\s*Name:\s*(\S+)\s*$", line):
                technical = match.group(1).strip('"').strip("'")
                continue

            if match := re.match(r"\s*Description:\s*(.+?)\s*$", line):
                description = match.group(1).strip('"').strip("'")
                entries[skill_id] = description
                if technical:
                    # The icon files are named for the technical name, in
                    # lower case: item/nv_basic.bmp.
                    sprites[skill_id] = technical.lower()
                skill_id = None

    if not entries:
        print("no skills found — is that a skill_db.yml?", file=sys.stderr)
        return 1

    out = [HEADER]
    for skill_id in sorted(entries):
        # Go string escaping: the descriptions carry quotes in a few places.
        name = entries[skill_id].replace("\\\\", "\\\\\\\\").replace('"', '\\\\"')
        out.append('\t%d: "%s",\n' % (skill_id, name))
    out.append(MIDDLE)
    for skill_id in sorted(sprites):
        out.append('\t%d: "%s",\n' % (skill_id, sprites[skill_id]))
    out.append(FOOTER)

    sys.stdout.write("".join(out))
    print("generated %d skills" % len(entries), file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
