#!/usr/bin/env python3
"""Generate the job-id to sprite-name table from the client's own Lua tables.

A unit packet identifies what to draw by a numeric job id. Nothing in the
protocol says which sprite that is; the mapping lives in two compiled Lua
tables shipped inside the GRF, and without them a monster or NPC can only be
drawn by guessing, which resolves to a Novice and puts a person on screen
wherever a Poring stands.

    npcidentity.lub   jobtbl = { JT_PORING = 1002, ... }
    jobname.lub       JobNameTable[jobtbl.JT_PORING] = "PORING"

Joining them on the JT_ name gives id -> sprite name. Neither file can be read
by pairing constants off in order: Lua interns its constant pool, so a sprite
name used by two ids appears once and the pairs fall out of step. The
instructions are what say which constant is a key and which a value, so those
are what this reads.

Usage:
    gen.py <npcidentity.lub> <jobname.lub> > spritenames.go
"""

import sys

import lub


def resolve(proto, registers, operand):
    """The value an instruction operand refers to, or None if unknown.

    Only the smallest constant indices fit in an instruction's operand field,
    so most entries in these tables are loaded into a register by LOADK first.
    Following those is the difference between reading a hundred entries and
    reading all of them.
    """
    if lub.is_constant(operand):
        return proto.constants[lub.constant_index(operand)]
    return registers.get(operand)


def walk(path, handle_settable, handle_gettable=None):
    """Run every prototype's instructions, tracking what LOADK puts where."""
    for proto in lub.load(path):
        registers = {}
        for instruction in proto.code:
            op, a, b, c = lub.decode(instruction)

            if op == lub.OP_LOADK:
                registers[a] = proto.constants[lub.bx(instruction)]
            elif op == lub.OP_GETTABLE and handle_gettable is not None:
                handle_gettable(resolve(proto, registers, c))
            elif op == lub.OP_SETTABLE:
                handle_settable(resolve(proto, registers, b), resolve(proto, registers, c))


def read_ids(path):
    """JT_ name -> numeric id, from `jobtbl = { JT_X = N, ... }`."""
    ids = {}

    def settable(key, value):
        if isinstance(key, str) and isinstance(value, float):
            ids[key] = int(value)

    walk(path, settable)
    return ids


def read_names(path):
    """JT_ name -> sprite basename, from `JobNameTable[jobtbl.JT_X] = "name"`.

    Each entry compiles to a GETTABLE naming the key followed by a SETTABLE
    carrying the value, so the key has to be carried from one to the other.
    """
    names = {}
    pending = [None]

    def gettable(key):
        if isinstance(key, str):
            pending[0] = key

    def settable(_, value):
        if pending[0] is not None and isinstance(value, str):
            names[pending[0]] = value
        pending[0] = None

    walk(path, settable, gettable)
    return names


def go_string(value):
    """Quote a sprite name as a Go string literal.

    Names are not all plain: several carry a backslash, because the sprite sits
    in a subdirectory of the monster folder rather than directly in it.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    ids = read_ids(sys.argv[1])
    names = read_names(sys.argv[2])

    table = {}
    missing = 0
    models = 0
    for job, sprite in names.items():
        if job not in ids:
            missing += 1
            continue
        # A few entries name a Granny 3D model rather than a sprite. They are
        # drawn by the map renderer, not the sprite pipeline, and keeping them
        # here would mean a load that can only ever fail.
        if ".gr2" in sprite.lower():
            models += 1
            continue
        table[ids[job]] = sprite

    out = [
        "// Code generated by tools/spritenames/gen.py. DO NOT EDIT.",
        "//",
        "// Source: the client's own npcidentity.lub and jobname.lub, extracted",
        "// from the GRF. Regenerate after a client data update.",
        "",
        "package charsprite",
        "",
        "// spriteNames maps a unit's job id to the basename of its sprite.",
        "var spriteNames = map[int]string{",
    ]
    for job in sorted(table):
        out.append(f"\t{job}: {go_string(table[job])},")
    out.append("}")
    out.append("")

    print("\n".join(out))
    print(
        f"// {len(ids)} ids, {len(names)} names, {len(table)} joined, "
        f"{missing} names with no id, {models} 3D models skipped",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
