import type { SkillCatalogData } from "../skill-catalog-contract";
export const catalogFixture: SkillCatalogData = {
  source: "client tables",
  sourceVersion: "a".repeat(64),
  jobs: [
    { id: 2, name: "Mage", skills: [13, 10] },
    { id: 9, name: "Wizard", skills: [89] },
  ],
  skills: [
    {
      id: 13,
      name: "Soul Strike",
      icon: "mg_soulstrike",
      jobs: [2],
      hasInfo: true,
      kind: "Magic",
      target: "Attack",
      elements: ["Ghost"],
      hits: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
      castMs: [400],
      fixedMs: [100],
      bindings: [{ phase: "target", effects: ["EF_SOULSTRIKE"] }],
      studio: "preview",
      sources: ["internal/game/skills/skilleffects.go"],
    },
    {
      id: 10,
      name: "Sight",
      icon: "mg_sight",
      jobs: [2],
      hasInfo: true,
      kind: "Magic",
      target: "Self",
      elements: [],
      hits: [],
      castMs: [],
      fixedMs: [],
      bindings: [{ phase: "caster", effects: ["EF_SIGHT"] }],
      studio: "mapped",
      sources: ["internal/game/skills/skilleffects.go"],
    },
    {
      id: 89,
      name: "Storm Gust",
      icon: "wz_stormgust",
      jobs: [9],
      hasInfo: true,
      kind: "Magic",
      target: "Ground",
      elements: ["Water"],
      hits: [],
      castMs: [],
      fixedMs: [],
      bindings: [{ phase: "ground", effects: ["EF_STORMGUST"] }],
      studio: "mapped",
      sources: ["internal/game/skills/skilleffects.go"],
    },
  ],
};
